Traceback (most recent call last):
  File "/home/dazzy/CLIP/train_newloss.py", line 195, in <module>
    wandb.log(base_lrs)
  File "/home/dazzy/.conda/envs/CLIP/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dazzy/.conda/envs/CLIP/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dazzy/.conda/envs/CLIP/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dazzy/.conda/envs/CLIP/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1922, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/dazzy/.conda/envs/CLIP/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1636, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
